// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://saxtweofultxwpayuydr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNheHR3ZW9mdWx0eHdwYXl1eWRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMzM5NzIsImV4cCI6MjA2NDgwOTk3Mn0.ejyidpXCRjVf6Ai6VJ6j4q96tfNtN73TbPCU-IZovNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});